### ISSUE TITLE
Huge repository means slow fetch

### ISSUE THREAD

**Issue by lox** [monmohan/xferspdy#15]
The repository took 8 minutes for me to fetch on a reasonably fast connection, I assume it's due to the large examples dir?

**Comment by shurcooL** [comment]
> The repository took 8 minutes for me to fetch on a reasonably fast connection,

Was GitHub having issues at the time? It took 9.2 seconds for me. The repository appears to be 104.1 MB in size. That definitely seems larger than one would expect a Go package to be.

**Comment by monmohan** [comment]
@lox @shurcooL The big size is because of testdata. There are couple of large binary files in testdata folder 50 MB.
